### ISSUE TITLE
CI/CD, Build Process

### ISSUE THREAD

**Issue by hobbyquaker** [jens-maus/hm-iobroker#3]
Falls Ihr euch bei RedMatic inspiration holen wollt wie ihr das Packaging und Deployment automatisieren könnt - hier hab ich das Stichwortartig dokumentiert: https://github.com/HM-RedMatic/RedMatic/blob/master/BUILD.md

**Comment by jens-maus** [comment]
Danke. Wir sollten in der Tat mal zusammen mit @zautrix über die weiteren Schritte diskutieren. Du hattest mir ja eine Email geschrieben das du dich gerne beteiligen möchtest bzw. Input aus RedMatic in die Weiterentwicklung des hm-iobroker addons fliessen lassen. Ich denke Anfang der Woche komme ich endlich dazu mir die Änderungen von @zautrix in Gänze anzuschauen. Hatte nur kurz mal drüber geschaut und das Addon getestet und es funktioniert prinzipiell. Mein Plan wäre nun erst einmal seinen Fork in das Repo hier zu merken und dann das Repo an Ihn zu übergeben da ich sicher auf Dauer nicht dazu kommen werde dieses weiterzuentwickeln.

Und parallel dazu kann man sicherlich dann einige Dinge deiner RedMatic build Umgebung übernehmen. Ergibt sicherlich sinn. Werde es mir dann anschauen. Danke für die Info!

**Comment by hobbyquaker** [comment]
> hattest mir ja eine Email geschrieben das du dich gerne beteiligen möchtest 

Mja, "beteiligen" würd ich das nicht nennen. ;-) Was ich anbiete beschränkt sich "nur" darauf euch ein paar Tipps zu geben bezüglich automatisiertem Addon-Build-Prozess und den Fallstricken die es beim Einsatz von npm auf Buildroot gibt, sowie Fragen zu beantworten die evtl. aufkommen könnten falls ihr den Buildprozess von RedMatic anschaut.

**Comment by jens-maus** [comment]
@zautrix @hobbyquaker 
So, hab die Änderungen von zautrix nun integriert in mein ursprüngliches repo und noch ein paar Kleinigkeiten geändert. Auch hab ich mir mal das build environment von RedMatic angeschaut und ich denke wir sollten das in der Tat so versuchen 1:1 für der ioBroker Addon zu übernehmen. Gefällt mir mit dem `build.sh` und dem damit verbundenen dynamischen zusammensuchen aller dependencies und auch mit dem automatischen node und npm installieren in das Addon Verzeichnis. Und das alles auch noch mit voller integration von travis, etc. :) Wäre in der tat einen versuch wert das für das ioBroker Addon zu übernehmen...

@zautrix Wie möchtest du nun weiter vorgehen bzw. was wäre dir am liebsten? Soll ich das Repo nun an deinen Nutzernamen übergeben und du gibst mir volle Schreibrechte damit ich direkt mithelfen kann oder belassen wir es erst einmal so wie es jetzt ist und ich gebe dir volle schreibrechte auf das repo hier? Weil bevor ich jetzt Anfange das build environment entsprechend von RedMatic zu übernehmen und für das hm-iobroker addon anzupassen sollten wir das prinzipiell geklärt haben. Auch habe ich als Lizenz nun mal die MIT Lizenz ausgewählt, einfach aus dem Grund heraus weil ioBroker auch unter MIT steht und es dann hoffentlich keine Konflikte geben sollte.

**Comment by zautrix** [comment]
@jens-maus  Wir können das Repo gerne erst einmal bei Dir belassen.
Die MIT Lizenz ist für mich ok.

**Comment by zautrix** [comment]
@jens-maus  Sooo, habe mal meinen fork deleted. Du könnstest jetzt zu mir umziehen.
